/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst } from 'workbox-strategies';

const API_BASE_URL = 'https://api-uec.onrender.com';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);


// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Configuración de endpoints de la API
//const API_BASE_URL = 'https://api-uec.onrender.com';
const API_ENDPOINTS = [
  '/api/songs/jovenes',
  '/api/songs/poder',
  '/api/songs/verde',
];

// Estrategia de caché para endpoints de la API de canciones
// Usa CacheFirst: sirve del caché primero, si no existe va a la red
// Sin expiración para mantener disponibles offline indefinidamente
registerRoute(
  ({ url, request }) =>
    request.method === 'GET' &&
    url.origin === API_BASE_URL &&
    url.pathname.startsWith('/api/songs/'),
  new CacheFirst({
    cacheName: 'api-songs-v1',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Estrategia NetworkFirst para endpoints de usuarios
// Prioriza datos frescos del servidor, usa cache solo si no hay red
registerRoute(
  ({ url }) =>
    url.origin === API_BASE_URL && url.pathname.startsWith('/api/users'),
  new NetworkFirst({
    cacheName: 'api-users-v1',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 5 * 60, // 5 minutos
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Estrategia StaleWhileRevalidate para otros endpoints de la API (canciones, etc.)
// Sirve caché inmediatamente y actualiza en segundo plano
registerRoute(
  ({ url }) => {
    return url.origin === API_BASE_URL && !url.pathname.startsWith('/api/users');
  },
  new StaleWhileRevalidate({
    cacheName: 'api-other-v1',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 1 día
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Handler de mensajes del service worker
// Permite comunicación bidireccional con la aplicación
self.addEventListener('message', (event) => {
  // Manejo de SKIP_WAITING para actualizaciones del service worker
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }

  // Manejo de invalidación manual del caché de TODAS las canciones
  if (event.data && event.data.type === 'CLEAR_SONGS_CACHE') {
    event.waitUntil(
      caches.open('api-songs-v1').then(async (cache) => {
        const urlsToDelete = API_ENDPOINTS.map(endpoint => 
          new Request(`${API_BASE_URL}${endpoint}`)
        );
        
        await Promise.all(
          urlsToDelete.map(url => cache.delete(url))
        );
        
        event.ports[0]?.postMessage({ 
          success: true, 
          message: 'Caché de canciones limpiado exitosamente' 
        });
      }).catch((error) => {
        event.ports[0]?.postMessage({ 
          success: false, 
          message: `Error al limpiar caché: ${error.message}` 
        });
      })
    );
  }

  // Manejo de invalidación manual del caché de un himnario específico
  if (event.data && event.data.type === 'CLEAR_HIMNARIO_CACHE') {
    const himnario = event.data.himnario;
    event.waitUntil(
      caches.open('api-songs-v1').then(async (cache) => {
        const urlToDelete = new Request(`${API_BASE_URL}/api/songs/${himnario}`);
        await cache.delete(urlToDelete);
        
        event.ports[0]?.postMessage({ 
          success: true, 
          message: `Caché de ${himnario} limpiado exitosamente` 
        });
      }).catch((error) => {
        event.ports[0]?.postMessage({ 
          success: false, 
          message: `Error al limpiar caché: ${error.message}` 
        });
      })
    );
  }
});

// Precargar los 3 himnarios al instalar el Service Worker
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open('api-songs-v1').then(async (cache) => {
      const promises = API_ENDPOINTS.map(endpoint => 
        fetch(`${API_BASE_URL}${endpoint}`, { mode: 'cors' })
          .then(response => {
            if (response.ok) {
              return cache.put(`${API_BASE_URL}${endpoint}`, response);
            }
          })
          .catch(error => {
            console.log(`No se pudo precargar ${endpoint}:`, error);
          })
      );
      await Promise.all(promises);
      console.log('Precarga de himnarios completada');
    })
  );
});